version: "3.5"
services:
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    networks:
      - default
    command: -dbhost mongo-db -logLevel DEBUG -corsOrigin __ALL -corsMaxAge 600
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data
       
networks:
  default:
    ipam:
      config:
        - subnet: 172.188.3.0/24

volumes:
  mongo-db: ~
  postgis-db: ~
