version: "3.5"
services:
  orion:
    image: fiware/orion:2.3.0
    hostname: orion
    container_name: orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -noCache -corsOrigin __ALL -corsMaxAge 600
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  # orion-ld:
  #   image: fiware/orion-ld
  #   hostname: orion-ld
  #   container_name: orion-ld
  #   expose:
  #     - "1026"
  #   ports:
  #     - "2026:1026"
  #   depends_on:
  #     - mongo-db
  #   networks:
  #     - default
  #   command: -dbhost mongo-db -logLevel DEBUG -noCache -corsOrigin __ALL -corsMaxAge 600

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data

  draco:
   image: ging/fiware-draco
   hostname: draco
   container_name: draco
   environment:
     - NIFI_WEB_HTTP_PORT=8081
   expose:
     - "8081"
     - "5050"
   networks:
     - default
   ports:
     - "8081:8081"
     - "5050:5050"
      
  lwm2m-iot-agent:
    image: fiware/lightweightm2m-iotagent
    hostname: lwm2m-iot-agent
    container_name: lwm2m-iot-agent
    depends_on:
      - mongo-db
    expose:
      - "4041"
      - "5683"
    ports:
      - "4041:4041"
      - "5683:5683"
    networks:
      - default
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongo-db"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent-lwm2m"
      - "LWM2M_PORT=5683"
        
  activemq:
    image: smaject/activemq
    hostname: activemq
    container_name: activemq
    expose:
      - "61616"
      - "8161"
    networks:
      - default
    ports:
      - "61616:61616"
      - "8161:8161"

  scorewater-gbg:
    container_name: scorewater-gbg
    hostname: scorewater-gbg
    build: scorewater-gbg
    depends_on:
      - activemq
      - orion
    networks:
      - default
    ports:
      - "8080:8080"
  
  postgis:
    hostname: postgis
    image: crunchydata/crunchy-postgres-gis:centos8-13.3-3.1-4.6.3
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - "MODE=postgres"
      - "PG_MODE=primary"
      - "PG_PRIMARY_USER=postgres"
      - "PG_PRIMARY_PASSWORD=password"
      - "PG_DATABASE=intern"
      - "PG_USER=testuser"
      - "PG_PASSWORD=password"
      - "PG_ROOT_PASSWORD=password"
      - "PG_PRIMARY_PORT=5432"

networks:
  default:
    ipam:
      config:
        - subnet: 172.188.3.0/24

volumes:
  mongo-db: ~
  # postgis-data-11: ~
