version: "3.5"
services:
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    networks:
      - default
    command: -dbhost mongo-db -logLevel DEBUG -corsOrigin __ALL -corsMaxAge 600
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data
        
  activemq:
    image: smaject/activemq
    hostname: activemq
    container_name: activemq
    expose:
      - "61616"
      - "8161"
      - "1883"
    networks:
      - default
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"
      
  
  postgis:
    hostname: postgis
    image: crunchydata/crunchy-postgres-gis:centos8-13.3-3.1-4.6.3
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - "MODE=postgres"
      - "PG_MODE=primary"
      - "PG_PRIMARY_USER=postgres"
      - "PG_PRIMARY_PASSWORD=password"
      - "PG_DATABASE=turbinator"
      - "PG_USER=turbinator"
      - "PG_PASSWORD=password"
      - "PG_ROOT_PASSWORD=password"
      - "PG_PRIMARY_PORT=5432"
    volumes:
      - postgis-db:/var/lib/postgresql/data

networks:
  default:
    ipam:
      config:
        - subnet: 172.188.3.0/24

volumes:
  mongo-db: ~
  postgis-db: ~
