version: "3.5"
services:
  orion:
    image: fiware/orion
    hostname: orion
    container_name: orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    networks:
      - default
    command: -dbhost mongo-db -logLevel DEBUG -corsOrigin __ALL -corsMaxAge 600
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data
        
  activemq:
    image: smaject/activemq
    hostname: activemq
    container_name: activemq
    expose:
      - "61616"
      - "8161"
      - "1883"
    networks:
      - default
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"
      
  perseo-core:
    image: telefonicaiot/perseo-core
    hostname: perseo-core
    environment:
      - PERSEO_FE_URL=http://perseo-fe:9090
      - MAX_AGE=6000
    networks:
      - perseo
    depends_on:
      - mongo-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure      

  perseo-fe:
    image: telefonicaiot/perseo-fe
    hostname: perseo-fe
    networks:
      - perseo
      - default
    ports:
      - 9090:9090
    depends_on:
      - perseo-core
    environment:
      - PERSEO_MONGO_ENDPOINT=mongo-db
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_LOG_LEVEL=debug
      - PERSEO_ORION_URL=http://orion:1026/
      - PERSEO_SMTP_HOST=www.hostname.com
      - PERSEO_SMTP_PORT=25
      - PERSEO_SMTP_SECURE=false
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
  
  postgis:
    hostname: postgis
    image: crunchydata/crunchy-postgres-gis:centos8-13.3-3.1-4.6.3
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - "MODE=postgres"
      - "PG_MODE=primary"
      - "PG_PRIMARY_USER=postgres"
      - "PG_PRIMARY_PASSWORD=password"
      - "PG_DATABASE=turbinator"
      - "PG_USER=turbinator"
      - "PG_PASSWORD=password"
      - "PG_ROOT_PASSWORD=password"
      - "PG_PRIMARY_PORT=5432"
    volumes:
      - postgis-db:/var/lib/postgresql/data

networks:
  default:
    ipam:
      config:
        - subnet: 172.188.3.0/24
  perseo:

volumes:
  mongo-db: ~
  postgis-db: ~
